# fly.toml file generated for backnode-pj4 on 2023-03-20T11:39:08+01:00

app = "backnode-pj4"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  FLY_APP_NAME = "backnode-pj4"
  MIX_ENV = "prod"
  PHX_HOST = "backnode-pj4.fly.dev"
  PORT = "5082"

[experimental]
  auto_rollback = true

[[services]]
  command = "npm start"
  http_checks = []
  internal_port = 5082
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
